In [ ]:
import pandas as pd

#find NA
df = pd.read_csv("../data/mouse_files/gene_set_list_mouse_2024.txt", sep="\t", header=None, dtype=str)
gene_cols = df.columns[1:]
df[df[gene_cols].isna().any(axis=1)]

                                                       0    1
68                                    mp_CLOVES_syndrome  NaN
95              mp_Charcot-Marie-Tooth_disease_type_2A2A  NaN
274                                    mp_MELAS_syndrome  NaN
398           mp_T-cell_adult_acute_lymphocytic_leukemia  NaN
1270              mp_abnormal_circulating_glucagon_level  NaN
1379   mp_abnormal_conjunctiva_goblet_cell_differenti...  NaN
1804              mp_abnormal_female_germ_cell_apoptosis  NaN
2713                       mp_abnormal_melanocyte_number  NaN
3113                       mp_abnormal_otic_pigmentation  NaN
4376                         mp_abnormal_uvea_morphology  NaN
5401                       mp_alveolar_soft_part_sarcoma  NaN
6818                       mp_decreased_interferon_level  NaN
8084                              mp_epididymis_fibrosis  NaN
8085                           mp_epididymis_hypertrophy  NaN
8480                                 mp_hepatic_peliosis  NaN
8919   mp_increased_adipose_tissue_noradrenaline_turn...  NaN
9057       mp_increased_cardiac_neural_crest_cell_number  NaN
9361          mp_increased_epididymal_cell_proliferation  NaN
10368              mp_isolated_growth_hormone_deficiency  NaN
10769                         mp_multiple_system_atrophy  NaN
11398                         mp_prostate_adenocarcinoma  NaN
11469                           mp_rectourethral_fistula  NaN
12050                                    mp_spermatocele  NaN
12416                                    mp_triphalangia  NaN

In [ ]:
#drop all rows with NA
df = pd.read_csv("../data/mouse_files/gene_set_list_mouse_2024.txt", sep="\t", header=None, dtype=str)
df_clean = df.dropna()
df_clean.rename(columns={0: "phenotype"}, inplace=True)
df_clean["genes"] = df_clean.iloc[:, 1:].agg("\t".join, axis=1)
df_clean = df_clean[["phenotype", "genes"]]

df_clean.head(15)

,phenotype,genes
0,mp_17-beta_hydroxysteroid_dehydrogenase_3_defi...,HSD17B3
1,mp_2-aminoadipic_2-oxoadipic_aciduria,DHTKD1
2,mp_3-methylglutaconic_aciduria_type_3,OPA3
3,mp_3-methylglutaconic_aciduria_with_deafness__...,SERAC1
4,mp_46_XX_gonadal_dysgenesis,FANCL
5,mp_46_XY_sex_reversal,DHH
6,mp_ARC_syndrome,NA VIPAS39 VPS33B
7,mp_Adams-Oliver_syndrome,ISL1 NOTCH2NLB
8,mp_Aicardi-Goutieres_syndrome,ADAR MEOX2 TREX1
9,mp_Alagille_syndrome,JAG1 NOTCH2
10,mp_Albright_s_hereditary_osteodystrophy,GNAS PTHLH
11,mp_Alexander_disease,GFAP
12,mp_Allan-Herndon-Dudley_syndrome,SLC16A2
13,mp_Alstrom_syndrome,ALMS1
14,mp_Alzheimer_s_disease,ABCC1 APBA2 APOA4 APOE APP CAV1 CLU FGF14 HPRT...

In [4]:
df_clean.count()

phenotype    12600
genes        12600
dtype: int64

In [ ]:
# find duplicate genes
gene_counts = df_clean["genes"].value_counts()

gene_counts.head(20)

FGFR2          15
TP63           13
CFTR           10
CACNA1A         9
PTEN            9
HOXA1           9
DMP1            8
HOXA13          8
FOXC1           8
CHD7            8
FGFR3           8
PSPH            8
TGFB2           8
MORC2           7
HOXA1 HOXB1     7
CFHR4           7
EDNRA           6
HR              6
SOX9            6
FIGN            6
Name: genes, dtype: int64

In [10]:
#get only phenotype names
df_clean = df.iloc[:, [0]]
df_clean

                                                       0
0      mp_17-beta_hydroxysteroid_dehydrogenase_3_defi...
1                  mp_2-aminoadipic_2-oxoadipic_aciduria
2                  mp_3-methylglutaconic_aciduria_type_3
3      mp_3-methylglutaconic_aciduria_with_deafness__...
4                            mp_46_XX_gonadal_dysgenesis
...                                                  ...
12619                                      mp_xerostomia
12620                         mp_xiphoid_process_foramen
12621                               mp_yellow_coat_color
12622                       mp_zygomatic_arch_hypoplasia
12623                       mp_zygomatic_bone_hypoplasia

[12624 rows x 1 columns]

In [ ]:
#remove mp and replace _ with a space
df_clean.iloc[:, 0] = df_clean.iloc[:, 0].str.replace(r'^mp_', '', regex=True).str.replace(r'_', ' ', regex=True)
df_clean

                                                       0
0      17-beta hydroxysteroid dehydrogenase 3 deficiency
1                     2-aminoadipic 2-oxoadipic aciduria
2                     3-methylglutaconic aciduria type 3
3      3-methylglutaconic aciduria with deafness  enc...
4                               46 XX gonadal dysgenesis
...                                                  ...
12619                                         xerostomia
12620                            xiphoid process foramen
12621                                  yellow coat color
12622                          zygomatic arch hypoplasia
12623                          zygomatic bone hypoplasia

[12624 rows x 1 columns]

In [ ]:
df_clean.to_csv("../data/mouse_files/gene_set_list_mouse_2024_clean.txt", sep="\t", index=False, header=False)